package reporter

import (
	"fmt"
	"strings"
	"time"

	"github.com/aivar-tech/safeupgrade-agent/internal/analyzer"
	"github.com/aivar-tech/safeupgrade-agent/internal/executor"
	"github.com/aivar-tech/safeupgrade-agent/internal/scanner"
)

type UpgradeReport struct {
	GeneratedAt time.Time       `json:"generated_at"`
	Summary     Summary         `json:"summary"`
	Upgrades    []UpgradeDetail `json:"upgrades"`
	Skipped     []SkippedDetail `json:"skipped"`
	PRBody      string          `json:"pr_body"`
}

type Summary struct {
	TotalScanned int    `json:"total_scanned"`
	Outdated     int    `json:"outdated"`
	Upgraded     int    `json:"upgraded"`
	Skipped      int    `json:"skipped"`
	TestsPassed  bool   `json:"tests_passed"`
	Status       string `json:"status"`
}

type UpgradeDetail struct {
	Name             string  `json:"name"`
	From             string  `json:"from"`
	To               string  `json:"to"`
	RiskScore        float64 `json:"risk_score"`
	ChangelogSummary string  `json:"changelog_summary"`
}

type SkippedDetail struct {
	Name   string `json:"name"`
	Reason string `json:"reason"`
}

func Generate(scan *scanner.Report, analyses []analyzer.Result, result *executor.UpgradeResult) *UpgradeReport {
	report := &UpgradeReport{
		GeneratedAt: time.Now(),
		Summary: Summary{
			TotalScanned: scan.Total,
			Outdated:     scan.Outdated,
			Upgraded:     result.Upgraded,
			Skipped:      result.Skipped,
			TestsPassed:  result.TestsPassed,
			Status:       "SAFE",
		},
	}

	if !result.TestsPassed {
		report.Summary.Status = "FAILED"
	}

	analysisMap := make(map[string]analyzer.Result)
	for _, a := range analyses {
		analysisMap[a.Package] = a
	}

	for _, pkg := range result.Packages {
		if pkg.Status == "upgraded" {
			a := analysisMap[pkg.Name]
			report.Upgrades = append(report.Upgrades, UpgradeDetail{
				Name:             pkg.Name,
				From:             pkg.From,
				To:               pkg.To,
				RiskScore:        a.AnomalyScore,
				ChangelogSummary: a.ChangelogSummary,
			})
		} else {
			report.Skipped = append(report.Skipped, SkippedDetail{
				Name:   pkg.Name,
				Reason: pkg.Error,
			})
		}
	}

	report.PRBody = generatePRBody(report)
	return report
}

func generatePRBody(report *UpgradeReport) string {
	var sb strings.Builder

	sb.WriteString("## 🔒 SafeUpgrade — Automated Dependency Upgrade\n\n")
	sb.WriteString(fmt.Sprintf("**Status:** %s | **Tests:** %s\n\n",
		report.Summary.Status,
		boolToEmoji(report.Summary.TestsPassed)))

	sb.WriteString("### 📦 Upgrades\n\n")
	sb.WriteString("| Package | From | To | Risk |\n")
	sb.WriteString("|---------|------|----|------|\n")
	for _, u := range report.Upgrades {
		risk := "🟢 Low"
		if u.RiskScore > 0.5 {
			risk = "🟡 Medium"
		}
		if u.RiskScore > 0.8 {
			risk = "🔴 High"
		}
		sb.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n", u.Name, u.From, u.To, risk))
	}

	if len(report.Skipped) > 0 {
		sb.WriteString("\n### ⏭️ Skipped\n\n")
		for _, s := range report.Skipped {
			sb.WriteString(fmt.Sprintf("- **%s**: %s\n", s.Name, s.Reason))
		}
	}

	sb.WriteString("\n---\n")
	sb.WriteString("*Generated by SafeUpgrade Agent*\n")

	return sb.String()
}

func boolToEmoji(b bool) string {
	if b {
		return "✅ Passed"
	}
	return "❌ Failed"
}
